name: todo_list
description: A Todo list app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: 1.0.5

  # Comparing dart objects
  equatable: 2.0.5

  # State managment
  flutter_bloc: 8.1.3

  # Hooks / Widget lifecycle
  flutter_hooks: 0.20.0

  # Local Database
  floor: 1.4.2

  # Service Locator
  get_it: 7.6.0

  # SQLite Database
  sqflite: 2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.4.6
  floor_generator: 1.4.2
  flutter_lints: 2.0.2

flutter:
  uses-material-design: true
